name = "readwise-explorer"
main = "src/index.js"
compatibility_date = "2023-11-21"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX" # available within your Worker on env.VECTORIZE_INDEX
index_name = "explorer-index"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "explorer-database"
database_id = "63b67a5c-64a2-4237-804b-0d11c2d0baa7"
